[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[client]
showErrorDetails = true
toolbarMode = "auto"

[runner]
fastReruns = true
